### ISSUE TITLE
GPU Memory

### ISSUE THREAD

**Issue by Jayzhang2333** [MMOCKING/RadarCam-Depth#10]
Hi there, great work! I am just wondering how much GPU memory do you have to run the RC-Net. I have an 8-GB GPU and I was trying to run the rcnet_run_zju.py. I ran into CUDA out of memory error. Since it is a testing code, I assume it should not take that much of memory.

**Comment by MMOCKING** [comment]
I'm deeply sorry for not responding promptly due to the busyness of job seeking and graduation. Indeed, this part of the code is relatively cumbersome, with high computational overhead, and it requires a significant amount of GPU memory. In our future work, we will strive to improve the efficiency of the code. Thank you for your understanding.
