### ISSUE TITLE
Unable to reproduce global aligned monocular depth

### ISSUE THREAD

**Issue by Jeffrey-Moon** [MMOCKING/RadarCam-Depth#12]
I was trying to reproduce the global aligned monocular depth by editing the provided global_alignment.py. I got the monocular depth for the DPT-hybrid model (dpt_hybrid-midas-501f0c75.pt) and tried running the global aligned monocular depth by running the LS method and the RANSAC method. When doing so, the resulting global aligned monocular depth is very different from the given dpt_var global aligned monocular depth, and the MAE and RMSE come out as significantly higher as well. I wasn't expecting the exact same global aligned monocular depth since I didn't know which pre-trained model DPT-Hybrid referred to in the paper but I thought the result should somewhat be close to the given DPT+Var data. However, despite the difference in the depth values, when I look at the PNG files, the reproduced global aligned monocular depth looks almost identical which seems to me that the scaling information received from the global alignment is off. 

This is the reproduced global aligned monocular depth
![demo](https://github.com/user-attachments/assets/5f50018b-c883-44ac-8d8b-a196c8fc48f8)
When printing the actual values, it contains values ranging from 11.9023 to 18.6094.

and this is the corresponding global aligned monocular depth provided in the dataset.
![demo](https://github.com/user-attachments/assets/be4a0f07-eea0-4b24-8e64-3df1e371c8ef)
When printing the actual values, it contains values ranging from 4.9922 to 13.0312 on the first row.

Is there anywhere that I could find the Var method and the Const method listed in the paper? What might be the reason behind me being unable to reproduce the global aligned monocular depth? Or are these the correct values for the DPT + LS method? If you need me to provide any other details please let me know.

**Comment by MMOCKING** [comment]
Apologies for the delayed response due to my recent busy schedule. I’ve provided the pre-trained weights for DPT and MiDaS that I used, which you can access [here](https://pan.baidu.com/s/1owUFYBisYJGkibHPRhkntg?pwd=1897) (uploading now). These might be helpful for your work.

Additionally, you might consider constraining the upper and lower depth limits for the radar points, as well as defining different search intervals in the optimization algorithm. These adjustments could potentially enhance the effectiveness of the global alignment process.

Thank you for your understanding, and I hope these suggestions are useful. Please feel free to reach out if you have any more questions.
