### ISSUE TITLE
Failure in extracting dataset

### ISSUE THREAD

**Issue by AshwinDisa** [MMOCKING/RadarCam-Depth#14]
Hello,

I downloaded the zip file and tried to extract it but for some reason it fails for 3 files. I have attached the output below. Tried on 2 devices but the issue still persists. I am using the unzip package to extract files.

CorrelationId: 991f4dd7-e6d0-4fd7-8211-b5deb1958501
UTC DateTime: 08/16/2024 22:08:50

The following files/folders have not been downloaded
0. data/gt_interp.tar.xz
1. data/image.tar.xz
2. result/global_aligned_mono/dpt_var.tar.xz

Any help is appreciated.

Best,
Ashwin

**Comment by Jeffrey-Moon** [comment]
I had a similar problem and I just downloaded the tar.xz files individually. Try using `tar -xf` instead of `unzip` when extracting the files.

**Comment by AshwinDisa** [comment]
I see. I t tried downloading files individually but the 3 large files shown above fail to download at all times. I wonder if there is another way such as a drive link instead of onedrive. 
Thanks for the help though!

**Comment by MMOCKING** [comment]
I apologize for the inconvenience caused by the previous OneDrive link becoming invalid due to storage space being full. I have replaced it with a stable Baidu Netdisk link: https://pan.baidu.com/s/1owUFYBisYJGkibHPRhkntg?pwd=1897. The file is currently being uploaded to this folder, so please be patient. I sincerely apologize for any inconvenience this may have caused.
