### ISSUE TITLE
请问能提供百度云盘链接吗？你们的OneDrive盘下载不了

### ISSUE THREAD

**Issue by Contrail97** [MMOCKING/RadarCam-Depth#15]
I also would like to know other way to download the dataset, is there any download address for Baidu Netdisk?

**Comment by MMOCKING** [comment]
I apologize for the inconvenience caused by the previous OneDrive link becoming invalid due to storage space being full. I have replaced it with a stable Baidu Netdisk link: https://pan.baidu.com/s/1owUFYBisYJGkibHPRhkntg?pwd=1897. The file is currently being uploaded to this folder, so please be patient. I sincerely apologize for any inconvenience this may have caused.
